"""corrigindo campo no permission group

Revision ID: 10197a91d78a
Revises: 9fb421ddc398
Create Date: 2024-01-07 18:30:38.075824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10197a91d78a'
down_revision = '9fb421ddc398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
