"""corrigindo campo no permission group

Revision ID: 16bc1ac58957
Revises: 10197a91d78a
Create Date: 2024-01-07 18:39:01.055379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bc1ac58957'
down_revision = '10197a91d78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
