"""

Revision ID: 25258749ff60
Revises: b29d8f0d73ac
Create Date: 2024-01-12 23:55:44.737543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25258749ff60'
down_revision = 'b29d8f0d73ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
