"""adicionando relacao entre grupo de permissao e usuario

Revision ID: 6c01e2c9e1c2
Revises: 07eed56c1d2a
Create Date: 2024-01-07 20:27:12.936260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c01e2c9e1c2'
down_revision = '07eed56c1d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions_group_user_association',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('permission_group_id',
                              sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['permission_group_id'], [
                        'permissions_groups.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions_group_user_association')
    # ### end Alembic commands ###
