"""setando o default do is_active do user como falso

Revision ID: 8b2f86db2e56
Revises: 6c01e2c9e1c2
Create Date: 2024-01-09 16:13:14.917173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2f86db2e56'
down_revision = '6c01e2c9e1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
