"""corrigindo campo no permission group

Revision ID: 9fb421ddc398
Revises: c69969636b69
Create Date: 2024-01-07 18:25:01.040841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb421ddc398'
down_revision = 'c69969636b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions_groups', sa.Column(
        'name', sa.String(), nullable=False))
    op.drop_index('ix_permissions_groups_action',
                  table_name='permissions_groups')
    op.drop_constraint('uq_action', 'permissions_groups', type_='unique')
    op.create_index(op.f('ix_permissions_groups_name'),
                    'permissions_groups', ['name'], unique=False)
    op.create_unique_constraint('uq_name', 'permissions_groups', ['name'])
    op.drop_column('permissions_groups', 'action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions_groups', sa.Column(
        'action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_name', 'permissions_groups', type_='unique')
    op.drop_index(op.f('ix_permissions_groups_name'),
                  table_name='permissions_groups')
    op.create_unique_constraint('uq_action', 'permissions_groups', ['action'])
    op.create_index('ix_permissions_groups_action',
                    'permissions_groups', ['action'], unique=False)
    op.drop_column('permissions_groups', 'name')
    # ### end Alembic commands ###
