"""adicionando UniqueConstraint para tabela de permissao nao repetir permissao rotas com mesma acao

Revision ID: e90fc428a175
Revises: c414497a3c73
Create Date: 2024-01-07 14:37:42.683717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90fc428a175'
down_revision = 'c414497a3c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_action_path', 'permissions', ['route_id', 'action'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_action_path', 'permissions', type_='unique')
    # ### end Alembic commands ###
